-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 01, 2022 at 02:05 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pps_impex`
--

-- --------------------------------------------------------

--
-- Table structure for table `data`
--

CREATE TABLE `data` (
  `id` int(11) NOT NULL,
  `image_url` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `short_detail` varchar(255) NOT NULL,
  `detail` text NOT NULL,
  `type` enum('Generic','Ayurvedic','Homeopathic','Veterinary') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `data`
--

INSERT INTO `data` (`id`, `image_url`, `title`, `short_detail`, `detail`, `type`) VALUES
(1, 'IMG-6357d3940fa874.56241150.jpg', 'Baby Diapers', 'Teddyy Baby Diapers', 'The Teddyy Baby easy diaper pants specially design for Indian body type are easy to pull up and take off just like an underwear Baby Diaper Pants come with an Anti-Bacterial Super absorbent gel core that quickly locks fluid away while the water soluble wetness indicator tells you when it may be time to change The rapid distribution layer in Teddyy Baby Easy Diaper Pants evenly distributes the liquid while the leak-proof soft elastic edges prevent leakage. It\'s breathable cloth-like embossed top sheet cover ensures proper air circulation which prevents stuffiness Baby diaper pants small size are ideal for babies of weight ranging from 3 to 8 kilograms', 'Ayurvedic'),
(2, 'IMG-63383528bff371.17356163.jpg', 'Multani mitti', 'Balaji Multani mitti (Fuller\'s Earth)  ', 'This product is enriched with Multani Mitti properties, for bright skin and to get rid of from skin diseases. Excellent healthy products for the protection of body, skin and hair. The beauty products are not only to look good but a strong medium to protect skin, making the body healthy, pure and clean. The beauty products available in the market though, give feel-good but actually they are serious threat to the body.', 'Generic'),
(3, 'IMG-63381c9b736803.28836353.jpg', 'Zostum 2g', 'sulbactam and cefoperazone for injection', 'CEFOPERAZONE+SULBACTAM belongs to the group of medicines called antibiotics used to treat various bacterial infections such as respiratory tract (lungs) infection, urine infection, blood infection, meningitis (inflammation of the brain and spinal cord), gonorrhoea (sexually transmitted disease), skin, abdominal, bone, and joint infections. Bacterial infections are caused due to the multiplication of harmful bacteria inside or on the body. Infectious or harmful bacteria can make you sick and reproduce quickly in your body. These harmful bacteria produce chemicals known as toxins, which can damage tissue and make you sick. CEFOPERAZONE+SULBACTAM does not work against infections caused by the virus, including cold and flu.\r\n\r\nCEFOPERAZONE+SULBACTAM is a combination of two antibiotics, namely: Cefoperazone (cephalosporin antibiotic) and sulbactam (beta-lactamase inhibitor). Cefoperazone works by preventing the formation of bacterial cell covering, which is necessary for their survival. Thereby, kills the bacteria. On the other hand, sulbactam works by decreasing bacterial resistance and enhancing the activity of cefoperazone against the bacteria. Together, CEFOPERAZONE+SULBACTAM helps to treat bacterial infections.\r\n\r\nTake CEFOPERAZONE+SULBACTAM as prescribed by your doctor. You are advised to take CEFOPERAZONE+SULBACTAM for as long as your doctor has prescribed it for you depending on your medical conditions. You may experience diarrhoea, allergic reaction, abnormal liver function tests, and anaemia (low number of red blood cells). Most of these side effects of CEFOPERAZONE+SULBACTAM do not require medical attention and gradually resolve over time. However, if the side effects are persistent, reach out to your doctor.\r\n\r\nBefore starting CEFOPERAZONE+SULBACTAM, please inform your doctor if you have any allergy (against any antibiotic), kidney or liver problems. Do not take CEFOPERAZONE+SULBACTAM on your own as self-medication may lead to antibiotic-resistance in which antibiotics fail to act against specific bacterial infections. Consult your doctor before taking CEFOPERAZONE+SULBACTAM if you are pregnant or planning for pregnancy. Avoid taking CEFOPERAZONE+SULBACTAM if you are breastfeeding as CEFOPERAZONE+SULBACTAM may pass into breast milk. Avoid alcohol consumption while taking CEFOPERAZONE+SULBACTAM to prevent unpleasant side-effects', 'Generic'),
(4, 'IMG-63381dcb42cc78.77458553.jpg', 'Machine Gun', 'sildenafil citrate Tablets IP 200mg', 'Sildenafil is used to treat male sexual function problems (impotence or erectile dysfunction-ED). In combination with sexual stimulation, sildenafil works by increasing blood flow to the penis to help a man get and keep an erection.', 'Generic'),
(5, 'IMG-633823f9381f77.07306766.jpg', 'Solearwax Ear Drops', 'paradichlorobenzene benzocaine and turpentine oil ear drops', 'BENZOCAINE+CHLOROBUTANOL+PARADICHLOROBENZENE+TURPENTINE OIL belongs to the class of medications called ‘Otic agents’ used to treat pain caused by impacted earwax. BENZOCAINE+CHLOROBUTANOL+PARADICHLOROBENZENE+TURPENTINE OIL softens and clears the impacted earwax (accumulated earwax). Too much earwax build-up occurs due to an ear infection, inflammation, or injury, or other conditions such as bone deformations in the ear, skin diseases such as eczema (skin inflammation), or narrowed ear canals.\r\n\r\nBENZOCAINE+CHLOROBUTANOL+PARADICHLOROBENZENE+TURPENTINE OIL is a combination of four medicines: Paradichlorobenzene, Benzocaine, Chlorobutanol, and Turpentine oil. Paradichlorobenzene acts as a hydrating agent. It softens the ear wax by reducing its thickness. Benzocaine acts as a local anesthetic and prevents pain. Chlorobutanol also acts as a wax softener. It also has antibacterial properties. Turpentine oil acts as a lubricating agent. It can also help to relieve ear pain.\r\n\r\nBENZOCAINE+CHLOROBUTANOL+PARADICHLOROBENZENE+TURPENTINE OIL is available only for external (ears only) use in the form of ear drops. You should use this medicine as prescribed by your doctor. The common side-effects of BENZOCAINE+CHLOROBUTANOL+PARADICHLOROBENZENE+TURPENTINE OIL are difficulty sleeping, skin irritation, redness, and headache. These side-effects are usually mild and temporary that doesn’t require medical attention. However, inform your doctor immediately if any of these side-effects persist or get worsen.\r\n\r\nDo not take BENZOCAINE+CHLOROBUTANOL+PARADICHLOROBENZENE+TURPENTINE OIL if you are allergic to any of its contents. Do not use in patients with an inflamed ear canal, perforated eardrum, or eczema (skin inflammation) on the outer ear. Before taking BENZOCAINE+CHLOROBUTANOL+PARADICHLOROBENZENE+TURPENTINE OIL, inform your doctor if you have hearing problems (including deafness), intestinal problems (including blockage, swelling, ulcers), kidney problems, myasthenia gravis (neuromuscular disease), and Parkinson\'s disease. It is not recommended for use in children below 1 year of age. Inform your doctor if you are pregnant or breastfeeding.', 'Generic'),
(6, 'IMG-6338247b07dc74.54727505.jpg', 'Pyricol Eye Drops', 'Chloramphenicol & Dexamethasone Sodium Phosphate Eye drops', 'PCD Pharma franchise company in India-Hope to do business with the top PCD Pharma franchise company in India. If yes, then you have come to the right place. Pharma Franchise Companies is the only online catalog and B2B Pharma Marketplace for real companies and pharmaceutical distributors that can provide you with Pharma PCD and a monopoly pharmacy franchise. At PCD Pharma franchise companies, we are committed to providing you with genuine buyers and suppliers of Pharma PCD throughout PAN India. Those who are willing to set up a new pharmaceutical company should think of the PCD franchise model. \"Pharma Franchise Companies\" It is a quality-oriented organization dedicated to providing reliable, safe, and high-quality medicines at the best prices. All products are processed with predetermined high-quality ingredients and the latest technology. Using predefined and approved test methods, each product is strictly tested under the approved manufacturing formula.\r\nWe at Pharma Franchise Company provide you with the opportunity to establish a PCD/pharmaceutical franchise in India. Our company provides you with diversified multi-dimensional drug products, including eye drops, tablets, capsules, powders, dry syrups, granules, etc. The goal of our company is to make the franchise, monopoly PCD pharmacy, and pharmacy an undeniable drug management department. We have a group of experts who will help you establish a Pharma PCD organization without encountering any obstacles and difficulties. Since the first day, we have been working hard to make 100% efforts to expand our business image in many areas of India, including Chandigarh, Badi, Gujarat, Madhya Pradesh, Kerala, etc.\r\n\"Pharma Franchise Companies\" is a popular and trusted pharmaceutical company in the pharmaceutical field. We wholeheartedly provide each customer with high-quality products. Therefore, now, our mission is to promote the progress of manufacturing. Therefore, we are working hard to be the best third-party manufacturing company to prepare all products. We assist pharmaceutical companies that do not have assembly plants. We believe in bringing glory by providing the best and nature to all. Therefore, we understand their needs and help them meet their requirements. Also, we ensure to provide the highest quality products at reasonable prices. So if you are looking for the best and trustworthy manufacturing company. Therefore, you can only get all the best products from our company. ', 'Generic'),
(7, 'IMG-6338272b370e49.59396535.jpg', 'Syringe', 'BD Emrald Single Use Syringe', 'BD Emerald™ syringes are designed to provide comfort and stability during use due to a robust and textured retaining ring. This product is used for general purpose aspiration and injection of fluids and may be used with conventional or safety hypodermic needles, blunt fill needles and other ISO Luer compliant fittings.\r\n\r\nBD Emerald™ Syringes meet our highest standards for product quality while also reducing environmental impact by using up to 30% less material than other syringes*, as well as using non-toxic materials in the production process, and adhering to sustainable operations practices, including the use of renewable electricity at our manufacturing facilities.', 'Generic'),
(8, 'IMG-6338277da99e81.17989057.jpg', 'Gloves', 'Latex Surgical Gloves', '\r\nLatex medical examination medical grade latex examination gloves for all kinds of healthcare procedures and general usage. Basic features, high quality product. Good fit and softness ensures superior comfort. Beaded cuffs ensures easy removing and wearing. Easy to use without roll back', 'Generic'),
(9, 'IMG-633831683a3919.48753888.jpg', 'Dettol', 'Antiseptic Liquid', 'ANTISEPTIC LIQUID: Protects from 100 illness causing germs\r\nDISINFECTANT LIQUID: Antiseptic Liquid used to disinfect household items and surfaces\r\nMULTIPURPOSE CLEANER: Great for everyday personal and home hygiene\r\nUSAGE: Ideal to be used for First Aid, cleaning cuts and wounds\r\nDOCTOR RECOMMENDED: All Dettol products are recommended by the Indian Medical Association (IMA)\r\nsurface_recommendation: Skin, floor, Tile, fabric', 'Generic'),
(10, 'IMG-633834fd4c7641.85199652.jpg', 'Butox Deltamethrin', 'BUTOX VET 1L-DELTAMETHRIN 1.25%', 'For prevention and control of ectoparasitic infestations\r\nSuitable For	Cattle, buffaloes, sheep, goats, camels, horses, dogs, and pigs\r\nButox Pour-On is an easily-applied pour-on product based on the proven active ingredient, deltamethrin. It controls lice, biting flies and nuisance flies and provides control for 8-10 weeks which is longer than any other available product in this segment. The advanced formula penetrates the oily layer of the skin to provide complete coverage of the body and is rainfast to provide flexibility in all conditions. Butox Pour-On is also licensed for control of lice in sheep.', 'Veterinary'),
(11, 'IMG-6338480b684056.17250496.jpg', 'Ostopet Nutrition', 'Virbac Nutrition Ostopet', 'Reguler Supplement For Canine Feeding, Not For Medical Use\r\nThe Growth-Enhancing Supplement For Pups & Young Dogs In A Palatable Strawberry Flavor To Support Normal Growth & Development In Pups\r\nTo Help Improve The Immune Response And Reduce Susceptibility To Diseases\r\nCalcium supplement for dogsand cats', 'Veterinary'),
(12, 'IMG-6338491a804313.57833429.jpg', 'Oral Powder', 'Virbac Cephalexin veterinary oral powder IP', 'It is an oral antibiotic that is used to treat pyoderma and other bacterial skin infections in dogs and is used off label or extra-label in cats to treat pyoderma and some other types of skin infections.', 'Veterinary'),
(13, 'IMG-63384b3b99a957.48100374.jpg', 'Albendazole', 'Virbac Albendazole Oral Suspension IP', ' Albendazole Oral Suspension 10 ml belongs to a group of antiparasitic drugs called \'anthelmintic\' used to treat parasites worm infections like neurocysticercosis (infection caused by pork tapeworm) and cystic hydatid disease (infection caused by dog tapeworm). Additionally, Albendazole Oral Suspension 10 ml is also used to treat infections caused by roundworms, hookworms, threadworm, whipworm, pinworm, flukes, and other parasites. \r\n\r\nAlbendazole Oral Suspension 10 ml contains ‘Albendazole’ which works by inhibiting tubulin polymerisation. This causes metabolic disruption and energy depletion in the parasite, which leads to its immobilisation. Thereby, Albendazole Oral Suspension 10 ml kills the susceptible helminth and treats the infection. \r\n\r\nTake Albendazole Oral Suspension 10 ml as prescribed. You are advised to take Albendazole Oral Suspension 10 ml for as long as your doctor has prescribed it for you depending on your medical condition. You may experience certain common side-effects such as stomach pain, nausea, vomiting, headache, and dizziness in some cases. Most of these side-effects do not require medical attention and will resolve gradually over time. However, you are advised to talk to your doctor if you experience these side-effects persistently.\r\n\r\nAlbendazole Oral Suspension 10 ml might increase the chances of getting an infection; maintain proper hygiene, and try to stay away from people with infections, flu or cold. Consult your doctor if you notice unusual bleeding or bruising as you may bleed or bruise easily while taking Albendazole Oral Suspension 10 ml. Do not take Albendazole Oral Suspension 10 ml if you are pregnant or planning for pregnancy as it may cause foetal harm. Do not breastfeed during and for minimum 5 days after treatment with Albendazole Oral Suspension 10 ml. Albendazole Oral Suspension 10 ml may cause dizziness, so be cautious while driving. Albendazole Oral Suspension 10 ml can be given to children above 2 years if prescribed by the doctor. Keep your doctor informed about your health condition and medicines to rule out any side-effects.', 'Veterinary'),
(14, 'IMG-63381654d58cd9.13676108.jpg', 'Amino Acids syrup', 'Savavet VAAV Multivitamins and Essential Amino Acids Syrup for Birds, Cats and Dogs', 'VAAV is multi-vitamin and essential amino acid syrup. It provides vitamins and minerals which are necessary for growth and overall wellbeing of pets.\r\n\r\nVAAV fights fatigue, restores energy and fills nutritional gaps. It has unmatched palatability and is the perfect blend of 10 Vitamins and 10 Amino Acids.\r\n\r\nVAAV promotes growth & development, helps to maintain healthy skin & coat, prevents recurrent infections and helps in the recovery and provides strength during recovery from illnesses and injuries.', 'Veterinary'),
(15, 'IMG-633817047ad6a1.68009667.jpg', 'Topical cure spray', 'Natural Remedies Topicure Advanced 100 ml - Natural Spray for Comprehensive Topical Cure', 'The Topicure Spray is effective in all kinds of wounds, including Foot & Mouth disease (FMD) foot lesions, foot-rot, surgical wounds, wounds due to shearing in sheep, dermatomycosis etc.\r\nTopicure Spray effectively kills the maggots and prevents further re-infestation\r\nTopicure Spray possesses better spreadability & deeper penetration into the lesions\r\nTopicure Spray imparts stain to identify the treated animal/area of application and also ensures complete coverage of the wound with spray', 'Veterinary'),
(16, 'IMG-63381794bb42c0.61841960.jpg', 'Intacef Tazo', 'ceftriaxone and tazobactam for injection', 'The combination of ceftolozane and tazobactam is used to treat certain infections including urinary tract infections and infections of the abdomen (stomach area). It is also used to treat certain types of pneumonia that developed in people who are on ventilators or who were in a hospital. Ceftolozane is in a class of antibiotics called cephalosporins. It works by killing bacteria. Tazobactam is in a class called beta-lactamase inhibitor. It works by preventing bacteria from destroying ceftolozane. Antibiotics will not work for colds, flu, or other viral infections.', 'Veterinary'),
(17, 'IMG-6338181d9f9240.57254964.jpg', 'amoxirm forte', 'Virbac Ampicillin and Sulbactam Injection', 'The combination of ampicillin and sulbactam injection is used to treat certain infections caused by bacteria, including infections of the skin, female reproductive organs, and abdomen (stomach area). Ampicillin is in a class of medications called penicillin-like antibiotics. It works by stopping the growth of bacteria. Sulbactam is in a class of medications called beta-lactamase inhibitors. It works by preventing bacteria from destroying ampicillin.\r\n\r\nAntibiotics such as ampicillin and sulbactam injection will not work for colds, flu, or other viral infections. Using antibiotics when they are not needed increases your risk of getting an infection later that resists antibiotic treatment.', 'Veterinary'),
(18, 'IMG-6338192268ed68.21297652.jpg', 'Enrostrong-10%', 'enrofloxacin oral solution', 'Enrofloxacin Oral Solution relates to the group of quinolones and acts as a bactericidal against a wide range of bacteria. It is a ??nth?t?? ?h?m?th?r???ut?? ?g?nt from the ?l??? ?f th? qu?n?l?n? ??rb?x?l?? ???d d?r?v?t?v??. Enrofloxacin h?? ?nt?b??t?r??l ??t?v?t? against a broad ????trum ?f Gr?m n?g?t?v? and Gr?m ????t?v? b??t?r??.\r\n\r\nIt is important to note that AdvaCare’s enrofloxacin oral solution is for veterinary purposes only, and while there are types available for human use, you should only use the medication prescribed by a veterinary doctor or animal care specialist for an animal.', 'Veterinary'),
(19, 'IMG-633819b8339d66.61732586.jpg', 'Tribivet', 'Vitamin B1 B6 B12 Injeciton', ' It is typically used in patients with severe blood loss and in cases of emergency where the loss of Vitamins is required to be replenished immediately and instantly. Packed in ready to use Pre-Filled Syringes which prevents contamination and avoids any kind of infections due to the reduction in processes, the product is the most hygienic method of infusing Vitamin B1, B6 and B12 to the patients.', 'Veterinary'),
(20, 'IMG-63381a491d0b11.78059518.jpg', 'Anistamin ', 'chlorpheniramine maleate injection IP', 'Chlorpheniramine 4mg Injection is an anti-allergic medication used in the treatment of various allergic conditions. It works by blocking the action of histamine and provides relief from symptoms such runny nose, sneezing, itching, skin rashes, and watery eyes.\r\n\r\nThe most common side effect of this medicine is drowsiness. Other side effects include the inability to concentrate, lethargy, blurred vision, nausea, vomiting, and diarrhea. Avoid driving or activities that need a lot of attention while taking this medicine. If any of the side effects bother you, let your doctor know. There may be ways of reducing or preventing them.\r\n\r\nThe most common side effect of this medicine includes burning at the site of application, dizziness, nausea, and vomiting. Avoid driving or attention-seeking activity. If these bother you or appear serious, let your doctor know. There may be ways of reducing or preventing them. In some cases, it may cause dryness of mouth, so it is advised to drink more water, always carry sugar candy or maintain oral hygiene.\r\n\r\nBefore taking this medicine, let your doctor know if you have glaucoma or have any gastro related issues, or have high blood pressure. Inform your doctor if you are pregnant, or breastfeeding. Your doctor should also know about all other medicines you are taking as many of these may make this medicine less effective or change the way it works. Generally, it is advised to avoid alcohol while on treatment.', 'Veterinary'),
(22, 'IMG-63580ddd6e0b76.89147159.jpg', 'Zandu', 'Zandu Balm', 'Zandu Balm is the perfect solution for headaches, body aches, and cold. It is India’s no. 1 pain relief balm that provides instant and long-lasting relief from body pains of all kinds. An Ayurvedic solution that is 100% safe and effective.', 'Ayurvedic'),
(23, 'IMG-63580eaf4e6df1.72931613.jpeg', 'Dabur', 'Chywanprash', 'Chyawanprash (CP) is an Ayurvedic health supplement which is made up of a super-concentrated blend of nutrient-rich herbs and minerals. It is meant to restore drained reserves of life force (ojas) and to preserve strength, stamina, and vitality, while stalling the course of aging. Chyawanprash is formulated by processing around 50 medicinal herbs and their extracts, including the prime ingredient, Amla (Indian gooseberry), which is the world’s richest source of vitamin C. Chyawanprash preparation involves preparing a decoction of herbs, followed by dried extract preparation, subsequent mixture with honey, and addition of aromatic herb powders (namely clove, cardamom, and cinnamon) as standard. The finished product has a fruit jam-like consistency, and a sweet, sour, and spicy flavor. Scientific exploration of CP is warranted to understand its therapeutic efficacy. Scattered information exploring the therapeutic potential of CP is available, and there is a need to assemble it. Thus, an effort was made to compile the scattered information from ancient Ayurvedic texts and treatises, along with ethnobotanical, ethnopharmacological, and scientifically validated literature, that highlight the role of CP in therapeutics. Citations relevant to the topic were screened.', 'Ayurvedic'),
(24, 'IMG-635810bfa82390.37223297.jpg', 'Baidynath', 'Natural and Herbal Medicine', 'One of India’s most respected Companies, Shree Baidyanath Ayurved Bhawan Pvt. Ltd. (Kolkata), popularly known as Baidyanath, is the acknowledged leader of Ayurvedic know-how. Established in 1917, the Company has played a pioneering role in re-establishing ancient knowledge with modern research and manufacturing techniques.\r\n\r\nAYURVEDA is a 5000 year old Science of health care and herbal treatment. AYURVEDA, is highly effective in common and complicated ailments, assures long term relief and has no side effects.', 'Ayurvedic'),
(25, 'IMG-635811576c83c0.02528784.jpg', 'Nagarjuna', 'Medicine', '\r\n\r\nNagarjuna Ayurveda is one of the trend setters in health care sector which took effective steps to restore Ayurveda as the mainstream Health Management System. Nagarjuna has taken immense efforts in the manufacturing of quality Ayurvedic medicines, establishing health care centres and specialty clinics, conducting deep rooted research in various streams of Ayurveda, and reaching the healthcare solutions to the common man through its wide marketing network. ', 'Ayurvedic'),
(26, 'IMG-6358124ac377f8.03065450.jpeg', 'Sbl', 'securities-based lending ', 'SBL Bio-Combination 24 Tablet is a homoeopathic health tonic which helps in improving general health and strength in your body. It is helpful in reversing the ill effects of diseases such as Anaemia which cause debility and weakness. It is also helpful in curing sleep and digestive disorders.', 'Homeopathic'),
(27, 'IMG-6358130a3e53c5.48017027.jpg', 'Dr.Reckweg', 'Homeopathic Medicine', 'Homoeopathy, based on the simple principle of stimulating the body’s own healing response, is more popular than ever. At ROSHANLAL, our attempt is to bring you a comprehensive, user-friendly guide that shows you how to use homoeopathy to help heal common ailments.', 'Homeopathic'),
(28, 'IMG-635813da9f16a2.97638585.jpg', 'Dr.Wilmar', 'Schwabe Company', 'Dr Willmar Schwabe India, 150 Yrs\' Experience in Homoeopathy Medicine Now Available Online. Schwabe India Online Homeopathic Medicine Store. Get 100% Genuine Medicines at Best Prices. ISO Certified. Free Shipping. Buy Directly From Brand. No Side Effects.', 'Homeopathic');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `mobileNo` bigint(10) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `code` bigint(6) NOT NULL DEFAULT 0,
  `role` enum('owner','admin','user') NOT NULL DEFAULT 'user'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `name`, `mobileNo`, `email`, `password`, `code`, `role`) VALUES
(1, 'Dr Chirag Raval', 8980817983, 'ppsimpex16@gmail.com', 'Chirag@20', 725669, 'owner');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `data`
--
ALTER TABLE `data`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `data`
--
ALTER TABLE `data`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
